### ISSUE TITLE
wayland not enable by default

### ISSUE THREAD

**Issue by pugaizai** [flathub/one.ablaze.floorp#57]

**Comment by madoka773** [comment]
```
  - --socket=wayland
  - --socket=fallback-x11
```
I think it should be like this

**Comment by dominichayesferen** [comment]
Floorp has issues anyway currently on Wayland, iirc, owing to its Firefox ESR base.

I'll keep this open, though, so that it can be revisited when the ESR rebase occurs.

**Comment by fluoriteByte** [comment]
ive been using floorp with x11 disabled and its been running fine,
![Capture d’écran du 2024-07-31 13-55-47](https://github.com/user-attachments/assets/9926c3d0-7a78-4902-94d6-3d92edbb3f8f)

**Comment by dominichayesferen** [comment]
Good for you, to be fair.
The problem is not everyone is as lucky as you've been, in Floorp's Discord Server bug reports alone for example.

When Floorp rebases on 128, this issue WILL be re-explored - though by then it might just... use Wayland... anyway because of upstream changes between 115 and 128.

**Comment by dominichayesferen** [comment]
@pugaizai This should now be fixed - 128 rebase just happened

**Comment by Muko-Tabi** [comment]
seems to crash less for me on NVIDIA Wayland, but it still crash regardless, [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1908825#c65) maybe the issue for NVIDIA users like me
